### ISSUE TITLE
Place the Menubar inside its own view & controller.

### ISSUE THREAD

**Issue by brokenprogrammer** [brokenprogrammer/RapidTunes#41]
We have a lot of menubar buttons so the NavigationController would get confusing and maybe even out of hand. We have decided to split the menubar into its own FXML and Controller to improve the structure of the application.

**Comment by Issier** [comment]
Submitted a pull request with what I believe to be the resolution for this issue

**Comment by brokenprogrammer** [comment]
@Issier I will look at the PR tomorrow, I've scimmed through it and it looks really nice. Thanks!

**Comment by brokenprogrammer** [comment]
Resolved through PR #51 
Credits: @Issier @RyanJCollins
